### ISSUE TITLE
new learners for DA

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#217]
http://cran.r-project.org/web/packages/ascrda

http://cran.r-project.org/web/packages/sparseLDA

Maybe these could be added?

**Comment by Autodidact24** [comment]
Hi @jakob-r @berndbischl,

I went through the tutorial explaining creation of learners. I just wanted to reiterate the same in order to verify. So, learners are wrappers i.e. they call another function that does the real work but provides a different or more convenient (or more convenient for a specific purpose) interface to it or specific syntax. E.g LDA learner calls predict.lda from MASS. And then we define various parameters to specify the way we want input features to be interpreted.

The 2 packages that @berndbischl mentioned both perform quite complex functions. While I go through those, can one identify a package that is easier to get and write learner for it.

- Shubham

**Comment by berndbischl** [comment]
@Autodidact24 

> So, learners are wrappers i.e. they call an.....

Yes. That is kinda the "lowest" level of mlr. We need these wrappers to have a unified interface for the underlying learning algorithms. And in the constructor we add lots of "meta" information about the learner, so we can program on it.

**Comment by berndbischl** [comment]
> 2 packages that @berndbischl mentioned both perform quite complex functions

Actually you dont need to get every detail of the algorithm to "wrap" it. Eg. for sparseLDA::sda what don't you understand? You mainly need to understand the input / output behavior.....

**Comment by berndbischl** [comment]
See #257 , more general

Closing this here.
