### ISSUE TITLE
nodeHarvest: NAs in predict

### ISSUE THREAD

**Issue by mllg** [berndbischl/mlr#218]
I had to move the nodeHarvest learners to todo-files, they sometimes produced NA and NaN in the predictions. 'test_learners_all.R' was triggering this.

Possible workaround: Impute random labels for classification and mean for regression.

**Comment by studerus** [comment]
I would rather write a bug report to the developer of `nodeHarvest` if it happens under normal circumstances.

**Comment by berndbischl** [comment]
@studerus Would you look at this / report it?
Otherwise we can close this.

**Comment by berndbischl** [comment]
@studerus 
ping

**Comment by studerus** [comment]
Yes, I will look at it.

**Comment by berndbischl** [comment]
@studerus 
another ping

**Comment by studerus** [comment]
I removed the missings properties as it does not seem to deal with missing data properly even though it says so in the documentation. I also set the number of nodes to 100 and the nodesize to 5 in test_all_learners because the test data set seems to be too small for the default settings. I hope it works now.

**Comment by studerus** [comment]
Sorry, I realized that it still does not pass the test in test_learners_classiflabelswitch. Unfortunately, even reducing the number of nodes or nodesize does not solve the problem. I already wrote an email to the maintainer of nodeHarvest. Can we switch off this test for nodeHarvest at the moment?

**Comment by berndbischl** [comment]
Hi
1) Please either solve this or remove of the learner again, so we dont break travis

2) I mean, in general we could disable a very specific test, but the labelswitch test seems quite important? Can you please explain what happens and why it would still be ok to have the learner in mlr?

**Comment by studerus** [comment]
I guess it has to do with the data set in the labelswitch test, in which the categories are perfectly separated. Somehow the current version of nodeHarvest can not deal with this rather artificial situation. It works with all other test data sets though. Therefore, I assume the nodeHarvest would work with more realistic data sets. I suggest that we leave it in for the moment and wait for the maintainer of nodeHarvest to respond. Can we make an exception in the labelswitch test for the time beeing in order to not break travis? If the maintainer does not want to solve the bug, we can take it out again. Personally, I do not really need this learner. I just integrated it because its also contained in `caret`.

**Comment by berndbischl** [comment]
Thx for the eplanation.
In that case do you want to add an "if" statement in the test, with a fixme comment, to skip that test?

**Comment by studerus** [comment]
I just received an answer from the maintainer of nodeHarvest. He said that he could already fix the bug and that he has sent an updated version to CRAN.

**Comment by berndbischl** [comment]
then we need to depend on the version in the SUGGESTs in DESCRIPTION

**Comment by studerus** [comment]
Unfortunately, even with the updated version of nodeHarvest I could not get it to pass the labelswitch test. I wrote another email to the maintainer and hope that he can solve it. I therefore made a temporary exception in the labelswitchtest.

**Comment by berndbischl** [comment]
Any news on this?

**Comment by studerus** [comment]
Unfortunately not. I just wrote another reminder to the maintainer of the package.

**Comment by berndbischl** [comment]
Ok, but thx for the feedback!
